- name: copy file repository default setup mariadb
  template:
    src: mariadb.repo
    dest: /etc/yum.repos.d/mariadb.repo

- name: Clear cache yum
  shell: yum clean all

- name: MariaDB packages are installed
  yum:
    pkg: '{{ item }}'
    state: installed
  with_items:
    - MySQL-python
    - MariaDB-cassandra-engine
    - MariaDB-client
    - MariaDB-common
    - MariaDB-compat
    - MariaDB-connect-engine
    - MariaDB-devel
    - MariaDB-oqgraph-engine
    - galera*
